server:
  port: 8070

spring:
  profiles:
    active: weiran
  application:
    name: cloud-manage
  datasource:
    admin:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cloud-manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456
    web:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cloud-mission?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456
    uaa:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cloud-uaa?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000 # 连接超时时间（毫秒）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  boot:
    admin:
      client:
        url: http://localhost:8890 # Spring Boot Admin 监控服务器端地址

security:
  jwt:
    token:
      secret-key: 6142b3c6f0e34477a899597cbd8ec45a2a5bd162415e617c0a32495215b8bc2ea01a3285149f94ae0f8a
      expire-length: 604800000

qiniu:
  # Access私钥
  accessKey: ENC(3yvK6uv/C/83akxjvhdsKje2PY+tPSWMIr9awy/A/G3I1f4SaiMUk4khCV524Sa/vwx2AYrC3og=)
  # Secret私钥
  secretKey: ENC(FrkBmkUKj/F/xGWEM7gZlKaP3cqiNV2I1aFGtr86I7mqMXUnWRNP5dibkvih4kcNgTd6OQHZtEk=)
  # 对象存储空间名
  bucket: weiran1999
  # 域名
  domain: http://rel.weiran.ltd/

management:
  endpoints:
    web:
      # 开放指定节点 /actuator/（info, health, beans, env, metrics）或者全部
      exposure:
        include: '*'
  # 在访问/actuator/health时显示完整信息
  endpoint:
    logfile:
      external-file: log/cloud-manage/manage.log

# 配置文件加密
jasypt:
  encryptor:
    # 密钥
    password: 123

logging:
  config: classpath:logback.xml